### ISSUE TITLE
定位 APP 元素时闪屏

### ISSUE THREAD

**Issue by iiFeng** [512433465/autotest_helper#1]
页面移动时会闪屏，底部驴妈妈的背景与我的页面混合显示，请问什么原因
![图片](https://dn-coding-net-production-pp.qbox.me/51d7b7f3-4ed7-4d53-b2d0-7791de2c97ba.png)
![图片](https://dn-coding-net-production-pp.qbox.me/b688d625-c39c-43cd-999f-a2959ae62a54.png)

https://dn-coding-net-production-pp.qbox.me/9a8c958f-9498-47ad-a0e0-df39067e6e41.gif

**Comment by 512433465** [comment]
非常抱歉，最近在忙自动部署开发的事情，忙完再修正吧。先坚持一下
