### ISSUE TITLE
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@14243dd4

### ISSUE THREAD

**Issue by qiaer** [512433465/autotest_helper#3]
已通过adb shell 查看LvmamaXmlKit.jar
java -XstartOnFirstThread -jar uiautomatorviewer-26.0.0-dev.jar
shell报错：文件加载异常：/var/folders/k5/5xsk3r9s4b7b9_k0qw7xw3bw0000gn/T/uiautomatorviewer_4402091181245857770/dump_1398279819454324593.uix
Lvmama UI Automator Viewer报错：Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@14243dd4
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@14243dd4

**Comment by 512433465** [comment]
非常非常抱歉，安卓端需要在Windows运行，我当初搞安卓端时没Mac机器，没有考虑到这个运行错误。
你在Windows环境下试试。非常抱歉

**Comment by qiaer** [comment]
> 非常非常抱歉，安卓端需要在Windows运行，我当初搞安卓端时没Mac机器，没有考虑到这个运行错误。
> 你在Windows环境下试试。非常抱歉

为啥说抱歉啊，有的用就不错了。。那我有空转到win上去试试

**Comment by 512433465** [comment]
恩，好的。

**Comment by Rain0193** [comment]
win 10 上也报这个错

> Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@20b1ab1
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@20b1ab1
