### ISSUE TITLE
解析XML文件出错

### ISSUE THREAD

**Issue by Joelone** [512433465/autotest_helper#4]
![screenshot from 2018-10-23 18-21-15](https://user-images.githubusercontent.com/1656353/47400075-86fca700-d6f0-11e8-8f54-be65f1003590.png)

Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@6589d966
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@6589d966

LvmamaXmlKit.jar已经复制到手机上
```
athene_f:/data/local/tmp # ls -l
total 1632
-rw-rw---- 1 shell shell   1118 2018-10-23 18:15 LvmamaXmlKit.jar
```

**Comment by lvkaicheng123** [comment]
遇到相同的错误，LvmamaXmlKit.jar已经复制到手机上，安卓8.1机器，求解决。

**Comment by 512433465** [comment]
安卓8.1使用不了。好久没有看了，等找一下解决方案。你先用安卓7一下的吧。
