### ISSUE TITLE
使用夜神模拟器

### ISSUE THREAD

**Issue by dksg8782** [512433465/autotest_helper#5]
无法截图，出来的图像是0kb，夜神模拟器和小米8SE都是这样的。
![default](https://user-images.githubusercontent.com/8927910/47959679-1b3a0880-e025-11e8-87a3-8d04c7052c2a.PNG)

**Comment by 512433465** [comment]
问题解决了么？模拟器应该没有问题的啊。LvmamaXmlKit.jar放到手机里了么？
